rpm-script: run scriptlets in /etc/kernel/{postinst,postrm}.d
openSUSE/suse-module-tools pull request #70
Opened 2023-03-21 13:49 UTC by mwilck

This is useful e.g. for DKMS, see bsc#1194723.

We run scripts in {/usr,}/etc/kernel/postinst.d in %post, and {/usr,}/etc/kernel/postrm.d in %postun. The /usr directories are included to make it possible to install scripts from packages without touching /etc.

Note: /etc/kernel/xyz will _not_ override /usr/etc/kernel/xyz; both scripts will be run.

See https://kernel-team.pages.debian.net/kernel-handbook/ch-update-hooks.html for similar functionality on Debian.

2023-03-24 14:48 UTC, hramrach requested changes

2023-03-24 14:48 UTC, hramrach commented on kernel-scriptlets/rpm-script
> +	run_parts /usr/etc/kernel/postinst.d /etc/kernel/postrm.d
both postrm?

2023-03-24 14:50 UTC, hramrach commented
Also doesn't DKMS need that uname_r passed to the script ?

2023-03-25 12:42 UTC, mwilck commented
Thanks for the review. Based on the recent discussion on BZ, I conclude this was wrong and short-sighted and I'll close it.

2023-03-25 12:42 UTC, closed without merging